name: el_saleh
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  sqflite: ^2.0.1
  intl: ^0.17.0
  get_storage: ^2.0.3
  get: ^4.6.1
  flutter_native_timezone: ^2.0.0
  date_picker_timeline: ^1.2.3
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  rxdart: ^0.27.2
  url_launcher: ^6.0.18
  flutter_slidable: ^1.2.0


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/whats.jpg
    - assets/el_raee.jpeg
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


